 version: "3.9" 
 
 services: 
   database: 
    image: postgres:latest 
    restart: always 
    environment: 
      POSTGRES_PASSWORD: verySecretPassword 
      POSTGRES_USER: administrator 
      POSTGRES_DB: server 
    volumes: 
      - ./data/db:/var/lib/postgresql/data 

   app: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always 
    environment: 
      SQLALCHEMY_DATABASE_URI: postgresql://administrator:verySecretPassword@database:5432/server 
    ports: 
      - "8080:8080" 
    # networks:
    #   - my_network 
    depends_on: 
      - database

#  networks:
#    my_network: