FROM python:3.10

RUN pip3 install poetry

WORKDIR /app

COPY pyproject.toml ./
RUN poetry install --no-root

COPY server server

CMD ["bash", "-c", "sleep 2 && poetry run flask --app server run --host 0.0.0.0 --port 8080"]